### ISSUE TITLE
Plugin no longer works with Rock v8.3

### ISSUE THREAD

**Issue by nathanp** [BricksandMortar/CheckInExtensions#2]
When trying to access any of the pages used by the plugin (Attendance Overview, Record Headcounts, etc.) the follow error is returned:

```
NotSupportedException

 in EntityFramework
Message
The specified type member 'GroupId' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.

Stack Trace

   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberAccessTranslator.TypedTranslate(ExpressionConverter parent, MemberExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.EqualsTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.BinaryTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.BinaryTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.BinaryTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.AggregateTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Plugins.com_bricksandmortarstudio.CheckInExtensions.HeadcountMetricValueList.BindGrid() in c:\inetpub\Rock\Plugins\com_bricksandmortarstudio\CheckInExtensions\HeadcountValueList.ascx.cs:line 338
   at Plugins.com_bricksandmortarstudio.CheckInExtensions.HeadcountMetricValueList.OnLoad(EventArgs e) in c:\inetpub\Rock\Plugins\com_bricksandmortarstudio\CheckInExtensions\HeadcountValueList.ascx.cs:line 109
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**Comment by wmsheeler** [comment]
We are experiencing the same problem on version 8.3

**Comment by JoshuaMaiorino** [comment]
Same in v.8.4

**Comment by arranf** [comment]
This is fixed and will be pushed to the rock store before this weekend

**Comment by nathanp** [comment]
Hi Arran,

I'm still getting these same errors in v1.2.1 of the plugin.

**Comment by knolly42** [comment]
Found an issue with the SQL in the migration source relating to schema changes on account of the new AttendanceOccurrence. Once fixed, I could get the Metric Hierarchy working, but the values are not populated by the sync job, so perhaps another issue to debug I guess.

**Comment by stewmystre** [comment]
Hey @knolly42 any chance of a pull request with your fixes? @arranf  any idea if this will still function with version 11.3 release? Are you still supporting this?
